### ISSUE TITLE
github 学习笔记

### ISSUE THREAD

**Issue by LogicStyle** [QuantAndrew/blog#2]
# tasklist
![tasklist](https://cloud.githubusercontent.com/assets/15081871/23736500/85e46ee0-04c7-11e7-8228-da4b2f7840c1.PNG)

# 表情
打冒号，可以自动填充表情。:
![default](https://cloud.githubusercontent.com/assets/15081871/23736521/9c78e37a-04c7-11e7-9960-6601903fec82.PNG)

#仓库的维护
通常来说clone 来的仓库实际上与原仓库并没有任何关系。所以我们需要将原仓库设置为远程仓库，从该仓库获取（fetch）数据与本地仓库进行合并（merge），让本地仓库的源代码保持最新状态。
![default](https://cloud.githubusercontent.com/assets/15081871/23928656/fac557e0-095b-11e7-9baf-0f25b39a80e6.PNG)

**Comment by QuantAndrew** [comment]
![Uploading 捕获.PNG…]()
